# Generated by Django 5.2.7 on 2025-10-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='classification',
            field=models.CharField(blank=True, choices=[('A', 'A (Muito Importante)'), ('B', 'B (Importante)'), ('C', 'C (Não essencial)'), ('D', 'D (Outros)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('R', 'Receita'), ('D', 'Despesa')], max_length=1, null=True),
        ),
    ]
