# Generated by Django 5.2.7 on 2025-10-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_category_classification_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountentry',
            name='type',
        ),
        migrations.AlterField(
            model_name='category',
            name='classification',
            field=models.CharField(choices=[('A', 'A (Muito Importante)'), ('B', 'B (Importante)'), ('C', 'C (Não essencial)'), ('D', 'D (Outros)')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], default='D', max_length=1),
        ),
    ]
