# Generated by Django 5.2.7 on 2025-10-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_accountentry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='financial_bucket',
            field=models.CharField(choices=[('ESS', 'Essenciais (Meta 50%)'), ('LAZ', 'Lazer / Desejos (Meta 30%)'), ('INV', 'Poupança / Investimentos (Meta 20%)'), ('NA', 'Não Aplicável (Ex: Receitas)')], default='NA', max_length=3),
        ),
    ]
