# Generated by Django 5.2.7 on 2025-10-22 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_category_financial_bucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Meta')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Alvo (R$)')),
                ('target_date', models.DateField(verbose_name='Data Prevista')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('linked_category', models.ForeignKey(help_text='Selecione a categoria onde os aportes para esta meta serão registrados.', limit_choices_to={'financial_bucket': 'INV', 'type': 'D'}, on_delete=django.db.models.deletion.PROTECT, to='finance.category', verbose_name='Categoria Vinculada (Poupança/Investimento)')),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
    ]
