# Generated by Django 5.2.7 on 2025-10-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
    ]
