# Generated by Django 5.2.7 on 2025-10-27 12:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_category_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Conta')),
                ('type', models.CharField(choices=[('CHECKING', 'Conta Corrente / Carteira'), ('SAVINGS', 'Poupança'), ('CREDIT_CARD', 'Cartão de Crédito'), ('INVESTMENT', 'Investimento'), ('OTHER', 'Outro')], default='CHECKING', max_length=20, verbose_name='Tipo de Conta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='accountentry',
            options={'ordering': ['-competence_date', '-date_added']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['type', 'name']},
        ),
        migrations.RemoveField(
            model_name='accountentry',
            name='date_payment',
        ),
        migrations.AddField(
            model_name='accountentry',
            name='competence_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data da Competência'),
        ),
        migrations.AddField(
            model_name='accountentry',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='finance.account', verbose_name='Conta'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Data da Transferência')),
                ('describe', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição (Opcional)')),
                ('account_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='finance.account', verbose_name='Conta de Destino')),
                ('account_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='finance.account', verbose_name='Conta de Origem')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
