# Generated by Django 5.2.7 on 2025-10-27 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_account_alter_accountentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountentry',
            name='installment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número da Parcela'),
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Compra')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('number_of_installments', models.PositiveSmallIntegerField(verbose_name='Número de Parcelas')),
                ('first_installment_date', models.DateField(verbose_name='Data da 1ª Parcela')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account', verbose_name='Conta (Cartão)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.category', verbose_name='Categoria')),
            ],
            options={
                'ordering': ['-first_installment_date'],
            },
        ),
        migrations.AddField(
            model_name='accountentry',
            name='installment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.installmentplan', verbose_name='Plano de Parcelamento'),
        ),
    ]
