# Generated by Django 5.2.7 on 2025-10-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_accountentry_installment_number_installmentplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountentry',
            name='date_payment',
            field=models.DateField(blank=True, help_text='Data que o valor foi debitado/creditado no banco.', null=True, verbose_name='Data do Pagamento (Opcional)'),
        ),
    ]
