# Generated by Django 5.2.7 on 2025-10-27 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_accountentry_date_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('describe', models.CharField(max_length=200, verbose_name='Descrição')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], max_length=10, verbose_name='Frequência')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Final (Opcional)')),
                ('last_generated_date', models.DateField(blank=True, editable=False, help_text='Última data em que um lançamento foi gerado para esta recorrência.', null=True)),
                ('next_due_date', models.DateField(blank=True, editable=False, help_text='Próxima data prevista para geração.', null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account', verbose_name='Conta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Transação Recorrente',
                'verbose_name_plural': 'Transações Recorrentes',
                'ordering': ['start_date', 'describe'],
            },
        ),
    ]
